### ISSUE TITLE
t.plan is slow

### ISSUE THREAD

**Issue by jamestalmage** [jfmengels/mocha-vs-ava-performance#1]
First, thanks for doing this. The AVA team appreciates it.

`t.plan` is pretty slow. It actually generates an Error and captures the stack trace every time you call it.

It's totally unnecessary for most sync tests, the only times you absolutely should use it are when there is **branching** or **async** behavior that might skip an assertion:
- Promise based tests with a `.catch` followed by `.then`
  
  ``` js
  test(t => {
    t.plan(2);
    return shouldRejectWithFoo().catch(err => {
      // The plan works here to ensure this rejection happens
      t.is(e.message, 'foo');
      return shouldResolveWithBar();
    }).then(result => t.is(result, 'bar'));
  });
  ```
- Guaranteeing multiple callbacks are called
  
  ``` js
  test.cb(t => {
    t.plan(2);
    const a = () => {
      // the use of `cb` mode, `t.plan` and `t.end` ensures b is called first (and only once), followed by a
      t.pass();
      t.end();
    };
    const b = () => t.pass();
    bThenA(a, b);
  });
  ```
- Ensuring a catch statement happens
  
  ``` js
  test(t => {
    t.plan(1);
    try {
       shouldThrow();
    } catch (err) {
      // normally t.throws() would be better, but we are testing a non-standard property here.
      t.is(err.foo, 'bar');
    }
  });
  ```

I am not arguing with your findings here. I am sure they are accurate. I am also sure your use of `t.plan` is not the only (or even primary) reason AVA is slower.

@sindresorhus - Maybe this should end up as a recipe as well.

**Comment by jamestalmage** [comment]
Just for reference:

``` js
import test from 'ava';

for(var i = 0; i < 10000; i++) {
  test(`test${i}`, t => {
    if (process.env.PLAN) {
      t.plan(1);
    }
    t.pass();
  });
}
```

Results:

```
PLAN=1 node cli.js --verbose lots-of-plans.js  6.48s user 0.65s system 119% cpu 5.942 total
node cli.js --verbose lots-of-plans.js  1.74s user 0.40s system 154% cpu 1.386 total
```

**Comment by sindresorhus** [comment]
> Maybe this should end up as a recipe as well.

:+1: Can you open an issue/PR on AVA about it?

**Comment by jamestalmage** [comment]
https://github.com/sindresorhus/ava/pull/482 mitigated most of the downside: 

```
PLAN=1 ava --verbose lots-of-plans.js  2.04s user 0.26s system 105% cpu 2.183 total
node ava --verbose lots-of-plans.js  1.42s user 0.26s system 110% cpu 1.526 total
```

**Comment by jamestalmage** [comment]
I will open a PR, but I think I'll play down the performance concern. I don't want people to avoid a good tool because they think it's "slow".

**Comment by sindresorhus** [comment]
@jamestalmage Yeah, the perf difference is negligible now. I mostly want it because of best practises.
